# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 815393a7effb71c3b0b8725907567aee5a1d1383eae698d2cd9475db20660c257fdd1ac362f4a88b15c52d67837cad7dc12e95d6cfb9db32cf64397f7f66ae65

test:
  secret_key_base: 09ee406876767aae160e4746247078d01160cda987f89e870c27f5566c16f858d4788a033acb0a93a61fa8dc44279500ef3e3195ac7ec664024302b21b038176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
